name: 'Pull Request Labeler'

on:
  - pull_request_target

jobs:
  labeler:
    uses: SP-Packages/actions/.github/workflows/pr-labeler.yml@v1.1.3
    permissions:
      contents: read
      pull-requests: write
